apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    env: test

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
        env: test

    spec:
      containers:
      - name: nginx
        image: nginx

      tolerations:
      - key: "node"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"
